---
title: "R Notebook"
output: html_notebook
---

```{r, Packages}
library(pacman)
p_load(
  reshape2,
  jsonlite,
  tidyverse,
  tm,
  topicmodels,
  parallel,
  tidytext,
  plotly,
  widyr,
  data.table,
  Morpho,
  pracma,
  plotly,
  lubridate,
  tidyr,
  LDAvis,
  servr,
  igraph,
  ggraph,
  gensimr,
  text2vec
)

```


```{r, Read Data}
source("DataCleaning.R")


```

```{r}
stop_ord <-
  read_delim(
    "https://gist.githubusercontent.com/berteltorp/0cf8a0c7afea7f25ed754f24cfc2467b/raw/305d8e3930cc419e909d49d4b489c9773f75b2d6/stopord.txt",
    delim = "\n",
    col_names = F
  )
stop_ord <- stop_ord %>% rename(lemma = X1)

stop_ord <- stop_ord$lemma %>% append(c("Note", "note", "al"))

stop_ord <- as.data.frame(stop_ord) %>% rename(lemma = stop_ord)
```


```{python}
import timeit
import pandas as pd
import text_to_x as ttx

start = timeit.timeit()
print("start")
print("test1")
print("test2")
ttt = ttx.TextToTokens(lang = "da", ner = "flair")
print("test3")
dataTexts=pd.read_csv("data.csv")
print("test4")
allTexts = dataTexts["text"]
print("test5")
ttt.texts_to_tokens(allTexts)
print("test6 ")
full_dfs = ttt.get_token_dfs()
print("end")
end = timeit.timeit()
print(end - start)
```

```{r}
py <- reticulate::py_run_string("")

full_df <- bind_rows(py$full_dfs, .id = "ID")

colnames(full_df)
full_df<- full_df %>% select(c("ID","n_sent","token","lemma","upos","ner"))
str(full_df)

full_df <- df1 %>% tibble::rowid_to_column( "ID") %>% mutate(ID = as.character(ID))%>% select(c("ID","paper"), "date") %>%  merge(full_df, by = "ID")

full_df %>% write.csv("full_tokenized_data.csv")

full_df %>% saveRDS("full_tokenized_data.rds")

```

```{r}
# dataframe <- read_csv("full_tokenized_data.csv") %>%
#   select(c(ID,date,paper,lemma,upos,ner))
# 
df <- readRDS("full_tokenized_data.rds") %>% select(c(ID,date,paper,lemma,upos,ner))

```


```{r}
df <- df %>%
  mutate(
    CoronaStatus = case_when(
      date < ymd("2020-02-26") ~ "Baseline",
      date > ymd("2020-02-28") & date < ymd("2020-04-12") ~ "Outbreak",
      date > ymd("2020-04-12") ~  "PostOutbreak"
    )
  ) %>% 
  drop_na()
```

```{r}

df2 <-
  df %>% filter(upos %in% c("VERB", "NOUN", "ADV", "PROPN", "ADJ")) %>%
  anti_join(stop_ord) %>% group_by(ID) %>% mutate(text = glue::glue_collapse(paste(lemma,upos, sep = "_"), " ")) %>% select(c("ID", "date", "paper", "CoronaStatus", "text")) %>% unique()

df2 %>% saveRDS("lemmatizedAndTaggedTexts.rds")

```
